# Generated by Django 3.2.6 on 2021-09-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
